---
version: "2.1"
services:
  webtop:
    image: webtoptor
    container_name: webtoptor
    privileged: true #optional
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/config
    ports:
      - 3000:3000
    shm_size: "4gb" #optional
    restart: unless-stopped
